name: Simple PR Processor

on:
  pull_request:
    types: [closed]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR was closed"
      - run: echo "Event name ${{ github.event_name }}"
      - run: echo "PR merged ${{ github.event.pull_request.merged }}"
